name: lint

on:
    push:
        branches: ["*"]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup node 20
              uses: actions/setup-node@v4
              with:
                  cache: "npm"
                  node-version: 22.7.0

            - name: npm ci
              run: npm ci

            - name: npm run lint
              run: npm run lint
